In [21]:
import pandas as pd

file_path1 = r"C:\Users\User\Downloads\book2.xlsx"  
file_path2 = r"C:\Users\User\Downloads\book3.xlsx"
excel_data1 = pd.read_excel(file_path1)
excel_data2 = pd.read_excel(file_path2)
print(excel_data1.head())
print(excel_data2.head())

  EMPLOYEE SALARY DATA        Unnamed: 1 Unnamed: 2           Unnamed: 3  \
0        EMPLOYEE NAME   SALARY PER HOUR      HOURS  TOTAL SALARY IN DAY
1           EMPLOYEES1               253    8 HOURS                 2000
2           EMPLOYEES2               253     7HOURS                 1750
3           EMPLOYEES3               253    6 HOURS                 1518
4           EMPLOYEES4               253    6 HOURS                 1518

               Unnamed: 4     Unnamed: 5        Unnamed: 6 Unnamed: 7
0  TOTAL SALARYY IN MONTH  AFTER 17% TAX  AFTER TAX SALARY  ROUND OFF
1                   60000          10200             49800      49800
2                   52500           8925             43575      43575
3                   45540         7741.8           37798.2      37798
4                   45540         7741.8           37798.2      37798
   Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN         NaN         NaN         NaN        NaN        NaN
1         NaN         NaN         NaN         NaN        NaN        NaN
2         NaN         NaN         NaN         NaN        NaN        NaN
3         NaN         NaN         NaN         NaN        NaN        NaN
4         NaN         NaN         NaN         NaN        NaN        NaN

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0        NaN        NaN        NaN        NaN         NaN         NaN
1        NaN        NaN        NaN        NaN         NaN         NaN
2        NaN        NaN        NaN        NaN         NaN         NaN
3        NaN        NaN        NaN        NaN         NaN         NaN
4        NaN        NaN        NaN        NaN         NaN         NaN

  Unnamed: 12
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

In [1]:
import pandas as pd
subjects = ["Urdu", "Physics", "Biology"]
index = ["Ali", "Amir", "Kamran", "Hashim"]

In [2]:
data = [
    [65, 76, 72],
    [87, 81, 88],
    [79, 73, 83],
    [82, 65, 96]
]

In [3]:
data_frames = pd.DataFrame(data, columns=subjects, index=index)

In [4]:
print(data_frames)

        Urdu  Physics  Biology
Ali       65       76       72
Amir      87       81       88
Kamran    79       73       83
Hashim    82       65       96

In [12]:
import pandas as pd

sales_data = pd.read_csv('employee_data1.csv', usecols=[0, 1])

In [13]:
print(sales_data)

      EmpID FirstName
0      1927    Turner
1      1928     Elvis
2      1929      Rose
3      1930     Frank
4      1931     Yurem
...     ...       ...
1495   3422    Jakobe
1496   3423    Adyson
1497   3424   Annabel
1498   3425    Kendra
1499   3426     Chace

[1500 rows x 2 columns]

In [14]:
import pandas as pd
sales_data = pd.read_csv('employee_data1.csv', skiprows=2)

In [15]:
print(sales_data)

      1928    Elvis     Daniels   8-Aug-22 Unnamed: 4  \
0     1929     Rose      Travis  27-Jul-23        NaN
1     1930    Frank    Williams  15-Jul-23        NaN
2     1931    Yurem     Donovan   9-Nov-22        NaN
3     1932     John       Smith  24-Dec-19  12-Jun-22
4     1933     Lynn    Daneault   8-Mar-19        NaN
...    ...      ...         ...        ...        ...
1493  3422   Jakobe    Erickson  22-Jun-22   7-Aug-22
1494  3423   Adyson  Strickland  28-Dec-20        NaN
1495  3424  Annabel     Wilkins   9-Dec-20   4-Aug-22
1496  3425   Kendra       Braun  28-May-19  23-Oct-21
1497  3426    Chace        Kerr  27-Apr-22        NaN

      Production Technician I      Cindy Phillips  \
0     Production Technician I           James Lee
1     Production Technician I        Kelly Vaughn
2     Production Technician I         Donna Jones
3               Sales Manager        Emily Gaines
4               Sales Manager         Laura Smith
...                       ...                 ...
1493  Production Technician I      Bethany Carter
1494  Production Technician I     Caroline Harris
1495  Production Technician I  Mr. James Castillo
1496  Production Technician I       Michael Woods
1497  Production Technician I       Javier Mccall

          elvis.daniels@bilearner.com  MSC                  Active  ...  \
0           rose.travis@bilearner.com  TNS                  Active  ...
1        frank.williams@bilearner.com  PYZ                  Active  ...
2         yurem.donovan@bilearner.com  WBL                  Active  ...
3            john.smith@bilearner.com  BPC                  Active  ...
4         lynn.daneault@bilearner.com  NEL                  Active  ...
...                               ...  ...                     ...  ...
1493    jakobe.erickson@bilearner.com  PYZ        Leave of Absence  ...
1494  adyson.strickland@bilearner.com  SVG                  Active  ...
1495    annabel.wilkins@bilearner.com  TNS  Voluntarily Terminated  ...
1496       kendra.braun@bilearner.com  WBL  Voluntarily Terminated  ...
1497         chace.kerr@bilearner.com  BPC                  Active  ...

              General - Con  17-03-1983  MA               Laborer  Female  \
0          Field Operations    3/3/1988  MA           Coordinator  Female
1             General - Con  26-08-1986  MA            Technician  Female
2                  Fielders  22-12-1999  MA              Engineer  Female
3             General - Sga  16-08-1977  MA       Project Manager    Male
4                    Aerial   1/11/1989  VT               Lineman  Female
...                     ...         ...  ..                   ...     ...
1493              Engineers  23-06-1998  MA       Model Assistant  Female
1494              Engineers   10/6/2001  MA              Engineer    Male
1495  Wireline Construction  27-01-1997  MA               Laborer    Male
1496                 Aerial  28-05-1954  MA               Foreman  Female
1497       Field Operations   11/9/1990  MA  Warehouse Technician  Female

      89914  Hispanic   Widowed  Fully Meets  3
0     97011     Asian   Widowed  Fully Meets  3
1     70906     Asian    Single  Fully Meets  3
2     17678     White    Single  Fully Meets  3
3      1886     Other   Widowed  Fully Meets  3
4      5473     Black   Widowed  Fully Meets  3
...     ...       ...       ...          ... ..
1493  44500     Other   Widowed  Fully Meets  3
1494  35444     Black   Widowed  Fully Meets  3
1495   6608     White    Single  Fully Meets  2
1496   3807  Hispanic  Divorced  Fully Meets  2
1497  57487     White   Married  Fully Meets  2

[1498 rows x 26 columns]

In [30]:
import pandas as pd

file_path = "employee_data3.xlsx"
data = pd.read_excel(file_path)

In [31]:
data['GenderCode'].fillna("No Gender", inplace=True)
print(data.iloc[10:31])

    EmpID   FirstName  LastName  StartDate   ExitDate  \
10   1937    Maryjane      Choi 2022-03-30 2023-01-30
11   1938    Madalynn     Yates 2020-03-23        NaT
12   1939    Angelina      Peck 2019-06-06        NaT
13   1940       Dario      Shaw 2023-05-28        NaT
14   1941       Deven   Frazier 2021-02-03        NaT
15   1942        Jett      Kent 2019-07-30 2022-11-09
16   1943      Zander   Aguilar 2022-05-08 2022-11-17
17   1944  Alessandro    Chavez 2020-05-12        NaT
18   1945      Jaxson     Brady 2019-03-28 2022-12-10
19   1946    Giovanni  Whitaker 2019-07-22        NaT
20   1947       Karen   Goodman 2020-09-17        NaT
21   1948       Skyla   Lambert 2022-07-02 2022-08-09
22   1949     Ashlynn     Duffy 2019-11-30        NaT
23   1950    Lilliana    Walker 2023-07-21 2023-07-21
24   1951     Lindsay  Copeland 2020-08-26 2021-05-30
25   1952     Kristin   Mccarty 2020-05-16        NaT
26   1953     Barbara   Sutwell 2023-04-06 2023-05-24
27   1954      Lenora    Tejeda 2019-02-18 2022-10-31
28   1955     Ludwick   Harrell 2020-10-10        NaT
29   1956    Courtney  Beatrice 2021-05-15        NaT
30   1957      Melisa     Gerke 2019-05-13 2022-05-30

                       Title              Supervisor  \
10  Production Technician II          Kayla Peterson
11  Production Technician II          Donna Gonzalez
12  Production Technician II          Michele Riddle
13  Production Technician II          Stephanie Kerr
14  Production Technician II      Mackenzie Johnston
15  Production Technician II        William Thompson
16  Production Technician II         Timothy Wheeler
17  Production Technician II         Steve Macdonald
18             Sales Manager  Christopher Murray DDS
19  Production Technician II          James Mitchell
20             Sales Manager             John Chavez
21  Production Technician II       Teresa Williamson
22             Sales Manager     Kimberly Washington
23  Production Technician II      Stephanie Anderson
24             Sales Manager          Jeffery Snyder
25             Sales Manager           Abigail Marks
26   Production Technician I          Jeffrey Murphy
27  Production Technician II           Heather Riley
28   Production Technician I          Jonathan Huber
29   Production Technician I             Patrick Liu
30   Production Technician I               Jimmy Cox

                            ADEmail BusinessUnit          EmployeeStatus  ...  \
10      maryjane.choi@bilearner.com         CCDR  Voluntarily Terminated  ...
11     madalynn.yates@bilearner.com          TNS                  Active  ...
12      angelina.peck@bilearner.com          PYZ                  Active  ...
13         dario.shaw@bilearner.com          TNS                  Active  ...
14      deven.frazier@bilearner.com          PYZ                  Active  ...
15          jett.kent@bilearner.com          TNS  Voluntarily Terminated  ...
16     zander.aguilar@bilearner.com          PYZ  Voluntarily Terminated  ...
17  alessandro.chavez@bilearner.com          TNS                  Active  ...
18       jaxson.brady@bilearner.com          TNS  Voluntarily Terminated  ...
19  giovanni.whitaker@bilearner.com          WBL                  Active  ...
20      karen.goodman@bilearner.com          MSC                  Active  ...
21      skyla.lambert@bilearner.com          TNS  Voluntarily Terminated  ...
22      ashlynn.duffy@bilearner.com          MSC                  Active  ...
23    lilliana.walker@bilearner.com          TNS  Voluntarily Terminated  ...
24   lindsay.copeland@bilearner.com          SVG  Voluntarily Terminated  ...
25    kristin.mccarty@bilearner.com          TNS                  Active  ...
26    barbara.sutwell@bilearner.com           PL                  Active  ...
27      lenora.tejeda@bilearner.com          SVG  Voluntarily Terminated  ...
28    ludwick.harrell@bilearner.com          MSC                  Active  ...
29  courtney.beatrice@bilearner.com           PL                  Active  ...
30       melisa.gerke@bilearner.com          TNS  Voluntarily Terminated  ...

                 Division                  DOB State JobFunctionDescription  \
10              Engineers           25-03-1957    PA             Technician
11               Splicing           18-03-1957    MA             Technician
12       Field Operations  1942-05-03 00:00:00    PA               Engineer
13              Engineers  1942-07-08 00:00:00    MA        Project Manager
14              Engineers  1941-06-10 00:00:00    PA               Engineer
15  Wireline Construction  1964-11-02 00:00:00    MA                Laborer
16           Shop (Fleet)           23-03-1956    PA               Mechanic
17       Field Operations           20-08-1963    PA             Technician
18              Engineers           17-02-1977    MA               Engineer
19                 Aerial           22-07-1956    PA                Lineman
20          General - Sga           21-07-1982    PA                Manager
21               Splicing  1963-08-12 00:00:00    PA                Splicer
22       Field Operations  1950-04-04 00:00:00    PA             Technician
23               Splicing           24-03-1958    PA                Splicer
24                 Aerial  1960-09-10 00:00:00    MA                Foreman
25            Underground           31-07-1989    PA                Laborer
26   Finance & Accounting           20-02-1976    MA                    Cfo
27   Finance & Accounting           22-07-1968    MA         Administration
28       Field Operations  1998-04-04 00:00:00    MA               Engineer
29   Billable Consultants           18-12-1958    MA               Engineer
30       Field Operations           15-02-1975    MA                Manager

   GenderCode LocationCode  RaceDesc MaritalDesc Performance Score  \
10  No Gender        34825     Asian      Single       Fully Meets
11  No Gender        52524     Other      Single       Fully Meets
12  No Gender        19068     Asian     Married       Fully Meets
13  No Gender        18285     Asian     Widowed       Fully Meets
14     Female        13977  Hispanic     Widowed       Fully Meets
15     Female        37830     Other     Widowed       Fully Meets
16     Female        34057     White     Widowed       Fully Meets
17     Female        80132     Asian     Married       Fully Meets
18     Female        36863     White     Married       Fully Meets
19  No Gender        76522     Other     Widowed       Fully Meets
20  No Gender        42775     White      Single       Fully Meets
21     Female        46619     Black     Married       Fully Meets
22     Female        63764  Hispanic    Divorced       Fully Meets
23     Female        30495     Asian     Married       Fully Meets
24     Female        32929     Asian     Married       Fully Meets
25     Female        57392     Other    Divorced       Fully Meets
26     Female         2718     Asian    Divorced       Fully Meets
27     Female         2129     Other    Divorced       Fully Meets
28       Male         1776     White     Married       Fully Meets
29     Female         1915     Black     Married       Fully Meets
30     Female         2330     Asian     Widowed       Fully Meets

   Current Employee Rating
10                       3
11                       3
12                       3
13                       3
14                       3
15                       3
16                       3
17                       3
18                       3
19                       3
20                       3
21                       3
22                       3
23                       3
24                       3
25                       3
26                       3
27                       3
28                       3
29                       3
30                       3

[21 rows x 26 columns]

C:\Users\User\AppData\Local\Temp\ipykernel_13296\3104651970.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['GenderCode'].fillna("No Gender", inplace=True)

In [8]:
import pandas as pd

data = {
    "Age": [25, 36, 30, 27, 38, 42, 34],
    "Salary": [42000, 50000, 45000, 43000, 51000, 62000, 48000]
}
df = pd.DataFrame(data)

In [9]:
def min_max_normalize(column):
    return (column - column.min()) / (column.max() - column.min())
    
df['Normalized_Age'] = min_max_normalize(df['Age'])
df['Normalized_Salary'] = min_max_normalize(df['Salary'])

In [10]:

print("Original DataFrame:")
print(df[['Age', 'Salary']])
print("\nNormalized DataFrame:")
print(df[['Normalized_Age', 'Normalized_Salary']])

Original DataFrame:
   Age  Salary
0   25   42000
1   36   50000
2   30   45000
3   27   43000
4   38   51000
5   42   62000
6   34   48000

Normalized DataFrame:
   Normalized_Age  Normalized_Salary
0        0.000000               0.00
1        0.647059               0.40
2        0.294118               0.15
3        0.117647               0.05
4        0.764706               0.45
5        1.000000               1.00
6        0.529412               0.30

In [11]:
import pandas as pd

data = {
    "Age": [25, 36, 30, 27, 38, 42, 34],
    "Salary": [42000, 50000, 45000, 43000, 51000, 62000, 48000]
}
df = pd.DataFrame(data)

In [12]:
def standardize(column):
    return (column - column.mean()) / column.std()

df['Standardized_Age'] = standardize(df['Age'])
df['Standardized_Salary'] = standardize(df['Salary'])

In [13]:
print("Original DataFrame:")
print(df[['Age', 'Salary']])
print("\nStandardized DataFrame:")
print(df[['Standardized_Age', 'Standardized_Salary']])

Original DataFrame:
   Age  Salary
0   25   42000
1   36   50000
2   30   45000
3   27   43000
4   38   51000
5   42   62000
6   34   48000

Standardized DataFrame:
   Standardized_Age  Standardized_Salary
0         -1.330145            -0.990994
1          0.466718             0.189765
2         -0.513389            -0.548209
3         -1.003443            -0.843399
4          0.793420             0.337360
5          1.446825             1.960903
6          0.140015            -0.105425

In [17]:
import pandas as pd
import numpy as np

data = {
    'First Score': [100, 90, np.nan, 95],
    'Second Score': [30, 45, 56, np.nan],
    'Third Score': [np.nan, 40, 80, 98]
}

In [18]:
df = pd.DataFrame(data)
df_interpolated = df.interpolate(method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_7088\2121974248.py:2: FutureWarning: DataFrame.interpolate with method=bfill is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_interpolated = df.interpolate(method='bfill')

In [19]:
print("Original DataFrame:")
print(df)
print("\nDataFrame after Backward Interpolation:")
print(df_interpolated)

Original DataFrame:
   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

DataFrame after Backward Interpolation:
   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [1]:
import pandas as pd

data = pd.read_csv('PMC-Patients.csv')
print(data.iloc[0:3])
print(data.isnull()[0:12])

C:\Users\User\AppData\Local\Temp\ipykernel_14492\1259885246.py:3: DtypeWarning: Columns (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('PMC-Patients.csv')

  patient_id patient_uid        PMID                         file_path  \
0          0   7665777-1         NaN  comm/PMC007xxxxxx/PMC7665777.xml
1          1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2          2   7665777-3         NaN  comm/PMC007xxxxxx/PMC7665777.xml

                                               title  \
0  Early Physical Therapist Interventions for Pat...
1  Early Physical Therapist Interventions for Pat...
2  Early Physical Therapist Interventions for Pat...

                                             patient               age gender  \
0  This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]      M
1  A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]      M
2  One week after a positive COVID-19 result this...  [[57.0, 'year']]      M

                                   relevant_articles  \
0  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2  {'32320506': 1, '32293716': 1, '23219649': 1, ...

                                    similar_patients  ... Unnamed: 405  \
0  {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
1  {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
2  {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...          NaN

  Unnamed: 406 Unnamed: 407 Unnamed: 408 Unnamed: 409 Unnamed: 410  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN

  Unnamed: 411 Unnamed: 412 Unnamed: 413 Unnamed: 414
0          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN

[3 rows x 415 columns]
    patient_id  patient_uid   PMID  file_path  title  patient    age  gender  \
0        False        False   True      False  False    False  False   False
1        False        False  False      False  False    False  False   False
2        False        False   True      False  False    False  False   False
3        False        False  False      False  False    False  False   False
4        False        False   True      False  False    False  False   False
5        False        False  False      False  False    False  False   False
6        False        False   True      False  False    False  False   False
7        False        False  False      False  False    False  False   False
8        False        False   True      False  False    False  False   False
9        False        False  False      False  False    False  False   False
10       False        False  False      False  False    False  False   False
11       False        False  False      False  False    False  False   False

    relevant_articles  similar_patients  ...  Unnamed: 405  Unnamed: 406  \
0               False             False  ...          True          True
1               False             False  ...          True          True
2               False             False  ...          True          True
3               False             False  ...          True          True
4               False             False  ...          True          True
5               False             False  ...          True          True
6               False             False  ...          True          True
7               False             False  ...          True          True
8               False             False  ...          True          True
9               False             False  ...          True          True
10              False             False  ...          True          True
11              False             False  ...          True          True

    Unnamed: 407  Unnamed: 408  Unnamed: 409  Unnamed: 410  Unnamed: 411  \
0           True          True          True          True          True
1           True          True          True          True          True
2           True          True          True          True          True
3           True          True          True          True          True
4           True          True          True          True          True
5           True          True          True          True          True
6           True          True          True          True          True
7           True          True          True          True          True
8           True          True          True          True          True
9           True          True          True          True          True
10          True          True          True          True          True
11          True          True          True          True          True

    Unnamed: 412  Unnamed: 413  Unnamed: 414
0           True          True          True
1           True          True          True
2           True          True          True
3           True          True          True
4           True          True          True
5           True          True          True
6           True          True          True
7           True          True          True
8           True          True          True
9           True          True          True
10          True          True          True
11          True          True          True

[12 rows x 415 columns]

In [3]:
import pandas as pd

data = pd.read_csv('PMC-Patients.csv')
print(data.iloc[0:16])
print(data.notnull()[0:11])

C:\Users\User\AppData\Local\Temp\ipykernel_14492\4169561259.py:3: DtypeWarning: Columns (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('PMC-Patients.csv')

   patient_id patient_uid        PMID                         file_path  \
0           0   7665777-1         NaN  comm/PMC007xxxxxx/PMC7665777.xml
1           1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2           2   7665777-3         NaN  comm/PMC007xxxxxx/PMC7665777.xml
3           3   7665777-4  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
4           4   7665777-5         NaN  comm/PMC007xxxxxx/PMC7665777.xml
5           5   7665777-6  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
6           6   7665777-7         NaN  comm/PMC007xxxxxx/PMC7665777.xml
7           7   7665777-8  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
8           8   7665777-9         NaN  comm/PMC007xxxxxx/PMC7665777.xml
9           9  7665777-10  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
10         10  7665777-11  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
11         11   8674153-1  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml
12         12   8674153-2  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml
13         13   8674405-1  34956746.0  comm/PMC008xxxxxx/PMC8674405.xml
14         14   8674458-1  34956749.0  comm/PMC008xxxxxx/PMC8674458.xml
15         15   8674685-1  34956752.0  comm/PMC008xxxxxx/PMC8674685.xml

                                                title  \
0   Early Physical Therapist Interventions for Pat...
1   Early Physical Therapist Interventions for Pat...
2   Early Physical Therapist Interventions for Pat...
3   Early Physical Therapist Interventions for Pat...
4   Early Physical Therapist Interventions for Pat...
5   Early Physical Therapist Interventions for Pat...
6   Early Physical Therapist Interventions for Pat...
7   Early Physical Therapist Interventions for Pat...
8   Early Physical Therapist Interventions for Pat...
9   Early Physical Therapist Interventions for Pat...
10  Early Physical Therapist Interventions for Pat...
11  Deranged Liver Function Tests and Liver Insult...
12  Deranged Liver Function Tests and Liver Insult...
13  Goserelin Ovarian Ablation Failure in Premenop...
14  Treatment of Inferior Vena Cava Thrombosis by ...
15  Unusual Cutaneous Location of Langheransian Hi...

                                              patient               age  \
0   This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]
1   A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]
2   One week after a positive COVID-19 result this...  [[57.0, 'year']]
3   This 69-year-old male was admitted to the ICU ...  [[69.0, 'year']]
4   This 57-year-old male was admitted to the ICU ...  [[57.0, 'year']]
5   This 52-year-old male tested COVID-19 positive...  [[52.0, 'year']]
6   Paramedics found this 59-year-old female with ...  [[59.0, 'year']]
7   This 33-year-old female patient had typical CO...  [[33.0, 'year']]
8   This 66-year-old male patient was admitted to ...  [[66.0, 'year']]
9   A 66-year-old male started to present symptoms...  [[66.0, 'year']]
10  This 77-year-old male patient was transferred ...  [[77.0, 'year']]
11  A 45-year-old female was brought in by ambulan...  [[45.0, 'year']]
12  A 29-year-old male was brought to the hospital...  [[29.0, 'year']]
13  A 36-year-old G4P2 premenopausal woman with a ...  [[36.0, 'year']]
14  The patient was a 62-year-old male with a past...  [[62.0, 'year']]
15  We report a case of a 45-year-old woman, a non...  [[45.0, 'year']]

   gender                                  relevant_articles  \
0       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
3       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
4       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
5       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
6       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
7       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
8       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
9       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
10      M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
11      F  {'18703853': 1, '22644309': 1, '9510397': 1, '...
12      M  {'18703853': 1, '22644309': 1, '9510397': 1, '...
13      F  {'29510273': 1, '10953134': 1, '30258937': 1, ...
14      M  {'29396156': 1, '185006': 1, '15696057': 1, '2...
15      F  {'30281871': 1, '9611381': 1, '26966089': 1, '...

                                     similar_patients  ... Unnamed: 405  \
0   {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
1   {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
2   {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...          NaN
3   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
4   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
5   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
6   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
7   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
8   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
9   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
10  {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
11                   {'8674153-2': 2, '4208431-1': 1}  ...          NaN
12                   {'8674153-1': 2, '4208431-1': 1}  ...          NaN
13                                                 {}  ...          NaN
14                                                 {}  ...          NaN
15                                                 {}  ...          NaN

   Unnamed: 406 Unnamed: 407 Unnamed: 408 Unnamed: 409 Unnamed: 410  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN          NaN

   Unnamed: 411 Unnamed: 412 Unnamed: 413 Unnamed: 414
0           NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN

[16 rows x 415 columns]
    patient_id  patient_uid   PMID  file_path  title  patient   age  gender  \
0         True         True  False       True   True     True  True    True
1         True         True   True       True   True     True  True    True
2         True         True  False       True   True     True  True    True
3         True         True   True       True   True     True  True    True
4         True         True  False       True   True     True  True    True
5         True         True   True       True   True     True  True    True
6         True         True  False       True   True     True  True    True
7         True         True   True       True   True     True  True    True
8         True         True  False       True   True     True  True    True
9         True         True   True       True   True     True  True    True
10        True         True   True       True   True     True  True    True

    relevant_articles  similar_patients  ...  Unnamed: 405  Unnamed: 406  \
0                True              True  ...         False         False
1                True              True  ...         False         False
2                True              True  ...         False         False
3                True              True  ...         False         False
4                True              True  ...         False         False
5                True              True  ...         False         False
6                True              True  ...         False         False
7                True              True  ...         False         False
8                True              True  ...         False         False
9                True              True  ...         False         False
10               True              True  ...         False         False

    Unnamed: 407  Unnamed: 408  Unnamed: 409  Unnamed: 410  Unnamed: 411  \
0          False         False         False         False         False
1          False         False         False         False         False
2          False         False         False         False         False
3          False         False         False         False         False
4          False         False         False         False         False
5          False         False         False         False         False
6          False         False         False         False         False
7          False         False         False         False         False
8          False         False         False         False         False
9          False         False         False         False         False
10         False         False         False         False         False

    Unnamed: 412  Unnamed: 413  Unnamed: 414
0          False         False         False
1          False         False         False
2          False         False         False
3          False         False         False
4          False         False         False
5          False         False         False
6          False         False         False
7          False         False         False
8          False         False         False
9          False         False         False
10         False         False         False

[11 rows x 415 columns]

In [4]:
import pandas as pd

data = pd.read_csv('PMC-Patients.csv')
print(data.iloc[0:16])
print(data.isnull()[0:11])

C:\Users\User\AppData\Local\Temp\ipykernel_14492\4173567635.py:3: DtypeWarning: Columns (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('PMC-Patients.csv')

   patient_id patient_uid        PMID                         file_path  \
0           0   7665777-1         NaN  comm/PMC007xxxxxx/PMC7665777.xml
1           1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2           2   7665777-3         NaN  comm/PMC007xxxxxx/PMC7665777.xml
3           3   7665777-4  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
4           4   7665777-5         NaN  comm/PMC007xxxxxx/PMC7665777.xml
5           5   7665777-6  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
6           6   7665777-7         NaN  comm/PMC007xxxxxx/PMC7665777.xml
7           7   7665777-8  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
8           8   7665777-9         NaN  comm/PMC007xxxxxx/PMC7665777.xml
9           9  7665777-10  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
10         10  7665777-11  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
11         11   8674153-1  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml
12         12   8674153-2  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml
13         13   8674405-1  34956746.0  comm/PMC008xxxxxx/PMC8674405.xml
14         14   8674458-1  34956749.0  comm/PMC008xxxxxx/PMC8674458.xml
15         15   8674685-1  34956752.0  comm/PMC008xxxxxx/PMC8674685.xml

                                                title  \
0   Early Physical Therapist Interventions for Pat...
1   Early Physical Therapist Interventions for Pat...
2   Early Physical Therapist Interventions for Pat...
3   Early Physical Therapist Interventions for Pat...
4   Early Physical Therapist Interventions for Pat...
5   Early Physical Therapist Interventions for Pat...
6   Early Physical Therapist Interventions for Pat...
7   Early Physical Therapist Interventions for Pat...
8   Early Physical Therapist Interventions for Pat...
9   Early Physical Therapist Interventions for Pat...
10  Early Physical Therapist Interventions for Pat...
11  Deranged Liver Function Tests and Liver Insult...
12  Deranged Liver Function Tests and Liver Insult...
13  Goserelin Ovarian Ablation Failure in Premenop...
14  Treatment of Inferior Vena Cava Thrombosis by ...
15  Unusual Cutaneous Location of Langheransian Hi...

                                              patient               age  \
0   This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]
1   A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]
2   One week after a positive COVID-19 result this...  [[57.0, 'year']]
3   This 69-year-old male was admitted to the ICU ...  [[69.0, 'year']]
4   This 57-year-old male was admitted to the ICU ...  [[57.0, 'year']]
5   This 52-year-old male tested COVID-19 positive...  [[52.0, 'year']]
6   Paramedics found this 59-year-old female with ...  [[59.0, 'year']]
7   This 33-year-old female patient had typical CO...  [[33.0, 'year']]
8   This 66-year-old male patient was admitted to ...  [[66.0, 'year']]
9   A 66-year-old male started to present symptoms...  [[66.0, 'year']]
10  This 77-year-old male patient was transferred ...  [[77.0, 'year']]
11  A 45-year-old female was brought in by ambulan...  [[45.0, 'year']]
12  A 29-year-old male was brought to the hospital...  [[29.0, 'year']]
13  A 36-year-old G4P2 premenopausal woman with a ...  [[36.0, 'year']]
14  The patient was a 62-year-old male with a past...  [[62.0, 'year']]
15  We report a case of a 45-year-old woman, a non...  [[45.0, 'year']]

   gender                                  relevant_articles  \
0       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
3       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
4       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
5       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
6       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
7       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
8       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
9       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
10      M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
11      F  {'18703853': 1, '22644309': 1, '9510397': 1, '...
12      M  {'18703853': 1, '22644309': 1, '9510397': 1, '...
13      F  {'29510273': 1, '10953134': 1, '30258937': 1, ...
14      M  {'29396156': 1, '185006': 1, '15696057': 1, '2...
15      F  {'30281871': 1, '9611381': 1, '26966089': 1, '...

                                     similar_patients  ... Unnamed: 405  \
0   {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
1   {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
2   {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...          NaN
3   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
4   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
5   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
6   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
7   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
8   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
9   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
10  {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
11                   {'8674153-2': 2, '4208431-1': 1}  ...          NaN
12                   {'8674153-1': 2, '4208431-1': 1}  ...          NaN
13                                                 {}  ...          NaN
14                                                 {}  ...          NaN
15                                                 {}  ...          NaN

   Unnamed: 406 Unnamed: 407 Unnamed: 408 Unnamed: 409 Unnamed: 410  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN          NaN

   Unnamed: 411 Unnamed: 412 Unnamed: 413 Unnamed: 414
0           NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN

[16 rows x 415 columns]
    patient_id  patient_uid   PMID  file_path  title  patient    age  gender  \
0        False        False   True      False  False    False  False   False
1        False        False  False      False  False    False  False   False
2        False        False   True      False  False    False  False   False
3        False        False  False      False  False    False  False   False
4        False        False   True      False  False    False  False   False
5        False        False  False      False  False    False  False   False
6        False        False   True      False  False    False  False   False
7        False        False  False      False  False    False  False   False
8        False        False   True      False  False    False  False   False
9        False        False  False      False  False    False  False   False
10       False        False  False      False  False    False  False   False

    relevant_articles  similar_patients  ...  Unnamed: 405  Unnamed: 406  \
0               False             False  ...          True          True
1               False             False  ...          True          True
2               False             False  ...          True          True
3               False             False  ...          True          True
4               False             False  ...          True          True
5               False             False  ...          True          True
6               False             False  ...          True          True
7               False             False  ...          True          True
8               False             False  ...          True          True
9               False             False  ...          True          True
10              False             False  ...          True          True

    Unnamed: 407  Unnamed: 408  Unnamed: 409  Unnamed: 410  Unnamed: 411  \
0           True          True          True          True          True
1           True          True          True          True          True
2           True          True          True          True          True
3           True          True          True          True          True
4           True          True          True          True          True
5           True          True          True          True          True
6           True          True          True          True          True
7           True          True          True          True          True
8           True          True          True          True          True
9           True          True          True          True          True
10          True          True          True          True          True

    Unnamed: 412  Unnamed: 413  Unnamed: 414
0           True          True          True
1           True          True          True
2           True          True          True
3           True          True          True
4           True          True          True
5           True          True          True
6           True          True          True
7           True          True          True
8           True          True          True
9           True          True          True
10          True          True          True

[11 rows x 415 columns]

In [8]:
import pandas as pd

data = pd.read_csv('PMC-Patients.csv')
print(data.iloc[0:12])
print(data.fillna(0)[0:12])

C:\Users\User\AppData\Local\Temp\ipykernel_14492\1625305469.py:3: DtypeWarning: Columns (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('PMC-Patients.csv')

   patient_id patient_uid        PMID                         file_path  \
0           0   7665777-1         NaN  comm/PMC007xxxxxx/PMC7665777.xml
1           1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2           2   7665777-3         NaN  comm/PMC007xxxxxx/PMC7665777.xml
3           3   7665777-4  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
4           4   7665777-5         NaN  comm/PMC007xxxxxx/PMC7665777.xml
5           5   7665777-6  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
6           6   7665777-7         NaN  comm/PMC007xxxxxx/PMC7665777.xml
7           7   7665777-8  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
8           8   7665777-9         NaN  comm/PMC007xxxxxx/PMC7665777.xml
9           9  7665777-10  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
10         10  7665777-11  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
11         11   8674153-1  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml

                                                title  \
0   Early Physical Therapist Interventions for Pat...
1   Early Physical Therapist Interventions for Pat...
2   Early Physical Therapist Interventions for Pat...
3   Early Physical Therapist Interventions for Pat...
4   Early Physical Therapist Interventions for Pat...
5   Early Physical Therapist Interventions for Pat...
6   Early Physical Therapist Interventions for Pat...
7   Early Physical Therapist Interventions for Pat...
8   Early Physical Therapist Interventions for Pat...
9   Early Physical Therapist Interventions for Pat...
10  Early Physical Therapist Interventions for Pat...
11  Deranged Liver Function Tests and Liver Insult...

                                              patient               age  \
0   This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]
1   A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]
2   One week after a positive COVID-19 result this...  [[57.0, 'year']]
3   This 69-year-old male was admitted to the ICU ...  [[69.0, 'year']]
4   This 57-year-old male was admitted to the ICU ...  [[57.0, 'year']]
5   This 52-year-old male tested COVID-19 positive...  [[52.0, 'year']]
6   Paramedics found this 59-year-old female with ...  [[59.0, 'year']]
7   This 33-year-old female patient had typical CO...  [[33.0, 'year']]
8   This 66-year-old male patient was admitted to ...  [[66.0, 'year']]
9   A 66-year-old male started to present symptoms...  [[66.0, 'year']]
10  This 77-year-old male patient was transferred ...  [[77.0, 'year']]
11  A 45-year-old female was brought in by ambulan...  [[45.0, 'year']]

   gender                                  relevant_articles  \
0       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
3       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
4       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
5       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
6       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
7       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
8       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
9       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
10      M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
11      F  {'18703853': 1, '22644309': 1, '9510397': 1, '...

                                     similar_patients  ... Unnamed: 405  \
0   {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
1   {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
2   {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...          NaN
3   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
4   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
5   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
6   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
7   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
8   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
9   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
10  {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
11                   {'8674153-2': 2, '4208431-1': 1}  ...          NaN

   Unnamed: 406 Unnamed: 407 Unnamed: 408 Unnamed: 409 Unnamed: 410  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN

   Unnamed: 411 Unnamed: 412 Unnamed: 413 Unnamed: 414
0           NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN

[12 rows x 415 columns]
   patient_id patient_uid        PMID                         file_path  \
0           0   7665777-1           0  comm/PMC007xxxxxx/PMC7665777.xml
1           1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2           2   7665777-3           0  comm/PMC007xxxxxx/PMC7665777.xml
3           3   7665777-4  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
4           4   7665777-5           0  comm/PMC007xxxxxx/PMC7665777.xml
5           5   7665777-6  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
6           6   7665777-7           0  comm/PMC007xxxxxx/PMC7665777.xml
7           7   7665777-8  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
8           8   7665777-9           0  comm/PMC007xxxxxx/PMC7665777.xml
9           9  7665777-10  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
10         10  7665777-11  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
11         11   8674153-1  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml

                                                title  \
0   Early Physical Therapist Interventions for Pat...
1   Early Physical Therapist Interventions for Pat...
2   Early Physical Therapist Interventions for Pat...
3   Early Physical Therapist Interventions for Pat...
4   Early Physical Therapist Interventions for Pat...
5   Early Physical Therapist Interventions for Pat...
6   Early Physical Therapist Interventions for Pat...
7   Early Physical Therapist Interventions for Pat...
8   Early Physical Therapist Interventions for Pat...
9   Early Physical Therapist Interventions for Pat...
10  Early Physical Therapist Interventions for Pat...
11  Deranged Liver Function Tests and Liver Insult...

                                              patient               age  \
0   This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]
1   A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]
2   One week after a positive COVID-19 result this...  [[57.0, 'year']]
3   This 69-year-old male was admitted to the ICU ...  [[69.0, 'year']]
4   This 57-year-old male was admitted to the ICU ...  [[57.0, 'year']]
5   This 52-year-old male tested COVID-19 positive...  [[52.0, 'year']]
6   Paramedics found this 59-year-old female with ...  [[59.0, 'year']]
7   This 33-year-old female patient had typical CO...  [[33.0, 'year']]
8   This 66-year-old male patient was admitted to ...  [[66.0, 'year']]
9   A 66-year-old male started to present symptoms...  [[66.0, 'year']]
10  This 77-year-old male patient was transferred ...  [[77.0, 'year']]
11  A 45-year-old female was brought in by ambulan...  [[45.0, 'year']]

   gender                                  relevant_articles  \
0       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
3       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
4       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
5       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
6       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
7       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
8       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
9       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
10      M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
11      F  {'18703853': 1, '22644309': 1, '9510397': 1, '...

                                     similar_patients  ... Unnamed: 405  \
0   {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...            0
1   {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...            0
2   {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...            0
3   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
4   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
5   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
6   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
7   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
8   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
9   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
10  {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...            0
11                   {'8674153-2': 2, '4208431-1': 1}  ...            0

   Unnamed: 406 Unnamed: 407 Unnamed: 408 Unnamed: 409 Unnamed: 410  \
0             0            0            0            0            0
1             0            0            0            0            0
2             0            0            0            0            0
3             0            0            0            0            0
4             0            0            0            0            0
5             0            0            0            0            0
6             0            0            0            0            0
7             0            0            0            0            0
8             0            0            0            0            0
9             0            0            0            0            0
10            0            0            0            0            0
11            0            0            0            0            0

   Unnamed: 411 Unnamed: 412 Unnamed: 413 Unnamed: 414
0             0            0            0            0
1             0            0            0            0
2             0            0            0            0
3             0            0            0            0
4             0            0            0            0
5             0            0            0            0
6             0            0            0            0
7             0            0            0            0
8             0            0            0            0
9             0            0            0            0
10            0            0            0            0
11            0            0            0            0

[12 rows x 415 columns]

In [7]:
import pandas as pd
df = pd.read_csv('PMC-Patients.csv')
print(df.fillna (method='pad')[0:12])

C:\Users\User\AppData\Local\Temp\ipykernel_14492\291857992.py:2: DtypeWarning: Columns (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PMC-Patients.csv')
C:\Users\User\AppData\Local\Temp\ipykernel_14492\291857992.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna (method='pad')[0:12])

   patient_id patient_uid        PMID                         file_path  \
0           0   7665777-1         NaN  comm/PMC007xxxxxx/PMC7665777.xml
1           1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2           2   7665777-3  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
3           3   7665777-4  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
4           4   7665777-5  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
5           5   7665777-6  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
6           6   7665777-7  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
7           7   7665777-8  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
8           8   7665777-9  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
9           9  7665777-10  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
10         10  7665777-11  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
11         11   8674153-1  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml

                                                title  \
0   Early Physical Therapist Interventions for Pat...
1   Early Physical Therapist Interventions for Pat...
2   Early Physical Therapist Interventions for Pat...
3   Early Physical Therapist Interventions for Pat...
4   Early Physical Therapist Interventions for Pat...
5   Early Physical Therapist Interventions for Pat...
6   Early Physical Therapist Interventions for Pat...
7   Early Physical Therapist Interventions for Pat...
8   Early Physical Therapist Interventions for Pat...
9   Early Physical Therapist Interventions for Pat...
10  Early Physical Therapist Interventions for Pat...
11  Deranged Liver Function Tests and Liver Insult...

                                              patient               age  \
0   This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]
1   A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]
2   One week after a positive COVID-19 result this...  [[57.0, 'year']]
3   This 69-year-old male was admitted to the ICU ...  [[69.0, 'year']]
4   This 57-year-old male was admitted to the ICU ...  [[57.0, 'year']]
5   This 52-year-old male tested COVID-19 positive...  [[52.0, 'year']]
6   Paramedics found this 59-year-old female with ...  [[59.0, 'year']]
7   This 33-year-old female patient had typical CO...  [[33.0, 'year']]
8   This 66-year-old male patient was admitted to ...  [[66.0, 'year']]
9   A 66-year-old male started to present symptoms...  [[66.0, 'year']]
10  This 77-year-old male patient was transferred ...  [[77.0, 'year']]
11  A 45-year-old female was brought in by ambulan...  [[45.0, 'year']]

   gender                                  relevant_articles  \
0       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
3       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
4       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
5       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
6       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
7       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
8       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
9       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
10      M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
11      F  {'18703853': 1, '22644309': 1, '9510397': 1, '...

                                     similar_patients  ... Unnamed: 405  \
0   {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
1   {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...          NaN
2   {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...          NaN
3   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
4   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
5   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
6   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
7   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
8   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
9   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
10  {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...          NaN
11                   {'8674153-2': 2, '4208431-1': 1}  ...          NaN

   Unnamed: 406 Unnamed: 407 Unnamed: 408 Unnamed: 409 Unnamed: 410  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN

   Unnamed: 411 Unnamed: 412 Unnamed: 413 Unnamed: 414
0           NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN

[12 rows x 415 columns]

In [9]:
import pandas as pd
data = pd.read_csv('PMC-Patients.csv')
print(data.fillna (method='bfill')[0:12])

C:\Users\User\AppData\Local\Temp\ipykernel_14492\851573120.py:2: DtypeWarning: Columns (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('PMC-Patients.csv')
C:\Users\User\AppData\Local\Temp\ipykernel_14492\851573120.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(data.fillna (method='bfill')[0:12])

   patient_id patient_uid        PMID                         file_path  \
0           0   7665777-1  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
1           1   7665777-2  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
2           2   7665777-3  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
3           3   7665777-4  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
4           4   7665777-5  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
5           5   7665777-6  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
6           6   7665777-7  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
7           7   7665777-8  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
8           8   7665777-9  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
9           9  7665777-10  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
10         10  7665777-11  33492400.0  comm/PMC007xxxxxx/PMC7665777.xml
11         11   8674153-1  34956745.0  comm/PMC008xxxxxx/PMC8674153.xml

                                                title  \
0   Early Physical Therapist Interventions for Pat...
1   Early Physical Therapist Interventions for Pat...
2   Early Physical Therapist Interventions for Pat...
3   Early Physical Therapist Interventions for Pat...
4   Early Physical Therapist Interventions for Pat...
5   Early Physical Therapist Interventions for Pat...
6   Early Physical Therapist Interventions for Pat...
7   Early Physical Therapist Interventions for Pat...
8   Early Physical Therapist Interventions for Pat...
9   Early Physical Therapist Interventions for Pat...
10  Early Physical Therapist Interventions for Pat...
11  Deranged Liver Function Tests and Liver Insult...

                                              patient               age  \
0   This 60-year-old male was hospitalized due to ...  [[60.0, 'year']]
1   A 39-year-old man was hospitalized due to an i...  [[39.0, 'year']]
2   One week after a positive COVID-19 result this...  [[57.0, 'year']]
3   This 69-year-old male was admitted to the ICU ...  [[69.0, 'year']]
4   This 57-year-old male was admitted to the ICU ...  [[57.0, 'year']]
5   This 52-year-old male tested COVID-19 positive...  [[52.0, 'year']]
6   Paramedics found this 59-year-old female with ...  [[59.0, 'year']]
7   This 33-year-old female patient had typical CO...  [[33.0, 'year']]
8   This 66-year-old male patient was admitted to ...  [[66.0, 'year']]
9   A 66-year-old male started to present symptoms...  [[66.0, 'year']]
10  This 77-year-old male patient was transferred ...  [[77.0, 'year']]
11  A 45-year-old female was brought in by ambulan...  [[45.0, 'year']]

   gender                                  relevant_articles  \
0       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
1       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
2       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
3       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
4       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
5       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
6       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
7       F  {'32320506': 1, '32293716': 1, '23219649': 1, ...
8       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
9       M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
10      M  {'32320506': 1, '32293716': 1, '23219649': 1, ...
11      F  {'18703853': 1, '22644309': 1, '9510397': 1, '...

                                     similar_patients  ...  \
0   {'7665777-2': 2, '7665777-3': 2, '7665777-4': ...  ...
1   {'7665777-1': 2, '7665777-3': 2, '7665777-4': ...  ...
2   {'7665777-1': 2, '7665777-2': 2, '7665777-4': ...  ...
3   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
4   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
5   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
6   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
7   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
8   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
9   {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
10  {'7665777-1': 2, '7665777-2': 2, '7665777-3': ...  ...
11                   {'8674153-2': 2, '4208431-1': 1}  ...

                                         Unnamed: 405  \
0    a lymphotropic virus causing diseases ranging...
1    a lymphotropic virus causing diseases ranging...
2    a lymphotropic virus causing diseases ranging...
3    a lymphotropic virus causing diseases ranging...
4    a lymphotropic virus causing diseases ranging...
5    a lymphotropic virus causing diseases ranging...
6    a lymphotropic virus causing diseases ranging...
7    a lymphotropic virus causing diseases ranging...
8    a lymphotropic virus causing diseases ranging...
9    a lymphotropic virus causing diseases ranging...
10   a lymphotropic virus causing diseases ranging...
11   a lymphotropic virus causing diseases ranging...

                                         Unnamed: 406           Unnamed: 407  \
0    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
1    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
2    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
3    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
4    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
5    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
6    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
7    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
8    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
9    known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
10   known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea
11   known case of hypopharynx cancer - T2N1M0 on ...   complaints of nausea

   Unnamed: 408                                       Unnamed: 409  \
0      vomiting   fever and decreased appetite. Patient was cli...
1      vomiting   fever and decreased appetite. Patient was cli...
2      vomiting   fever and decreased appetite. Patient was cli...
3      vomiting   fever and decreased appetite. Patient was cli...
4      vomiting   fever and decreased appetite. Patient was cli...
5      vomiting   fever and decreased appetite. Patient was cli...
6      vomiting   fever and decreased appetite. Patient was cli...
7      vomiting   fever and decreased appetite. Patient was cli...
8      vomiting   fever and decreased appetite. Patient was cli...
9      vomiting   fever and decreased appetite. Patient was cli...
10     vomiting   fever and decreased appetite. Patient was cli...
11     vomiting   fever and decreased appetite. Patient was cli...

                                         Unnamed: 410      Unnamed: 411  \
0   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
1   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
2   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
3   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
4   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
5   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
6   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
7   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
8   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
9   diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
10  diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]
11  diagnosed with hepatitis C virus. Elevated liv...  [[14.0, 'year']]

   Unnamed: 412                                   Unnamed: 413  \
0             M  {'33996076': 1, '32631239': 1, '32429962': 2}
1             M  {'33996076': 1, '32631239': 1, '32429962': 2}
2             M  {'33996076': 1, '32631239': 1, '32429962': 2}
3             M  {'33996076': 1, '32631239': 1, '32429962': 2}
4             M  {'33996076': 1, '32631239': 1, '32429962': 2}
5             M  {'33996076': 1, '32631239': 1, '32429962': 2}
6             M  {'33996076': 1, '32631239': 1, '32429962': 2}
7             M  {'33996076': 1, '32631239': 1, '32429962': 2}
8             M  {'33996076': 1, '32631239': 1, '32429962': 2}
9             M  {'33996076': 1, '32631239': 1, '32429962': 2}
10            M  {'33996076': 1, '32631239': 1, '32429962': 2}
11            M  {'33996076': 1, '32631239': 1, '32429962': 2}

                                        Unnamed: 414
0   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
1   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
2   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
3   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
4   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
5   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
6   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
7   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
8   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
9   {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
10  {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}
11  {'7237229-1': 2, '7237229-2': 2, '7237229-4': 2}

[12 rows x 415 columns]